language: python
services:
  - docker
python:
  - '3.6'
script:
  - 'docker build -t ${TRAVIS_REPO_SLUG} .'
  - 'docker build -t dredd-tests . -f ./tests/Dockerfile'
  - 'docker-compose -f ./tests/docker-compose.yml up -d auth-redis postgres'
  - 'docker-compose -f ./tests/docker-compose.yml run auth'
after_success:
  - travis/publish.sh
